name: plugin
version: 0.2.0
author: BlackSalt Team <misc@dartlang.org>
description: Support for building plugins.
homepage: https://github.com/blacksaltIT/dart_graphql
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  analyzer: 0.32.4
  graphql_parser: any
  code_builder: 3.1.3
  json_object_lite: 2.0.0
  dart_style: any
  build: ^0.12.0
  build_runner: 0.10.2
  source_gen: 0.9.0+1
dev_dependencies:
  test: any
