name: dart_graphql
version: 0.4.1
description: Generates dart code for GraphQL endpoints using the original type names and all properties.
homepage: https://github.com/blacksaltIT/dart_graphql
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  graphql_parser: ^1.0.0
  json_object_lite: ^2.0.0
  code_builder: ^3.1.3
  build_runner: ^1.0.0

  dart_style: ^1.0.0
  build: ^1.0.0
  async: ^2.0.0
  http: ^0.12.0
  meta: ^1.0.0
  path: ^1.0.0

dev_dependencies:
  test: any
