name: dart_graphql
version: 0.2.0
author: BlackSalt Team <misc@dartlang.org>
description: Support for building plugins.
homepage: https://github.com/blacksaltIT/dart_graphql
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  graphql_parser: ^1.0.0
  json_object_lite: ^2.0.0
  code_builder: ^3.1.3
  build_runner: ^1.0.0

dev_dependencies:
  test: any
